{% set name = "ajc27-freemocap-blender-addon" %}
{% set version = "2025.1.1035" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ajc27_freemocap_blender_addon-{{ version }}.tar.gz
  sha256: b6e99c09ca05ad2bafcb3bd7afbd931ea83bd537f34902b2896e6b5229a6340d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - ajc27_freemocap_blender_addon
  commands:
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/freemocap/freemocap_blender_addon
  summary: A Blender Add-on for working with Freemocap Data (based on @ajc27's addon)
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
